### ISSUE TITLE
Exclude open/close of nested table from undo history

### ISSUE THREAD

**Issue by Dorus** [have-fun-was-taken/yafc-ce#23]
I'm not sure why this is in the undo history in the first place.

**Comment by shihan42** [comment]
Yeah, that is a nuisance I've seen in some programs. IMHO undo should not focus on UI changes (aside from some very specific niche cases).

**Comment by Dorus** [comment]
Note, i changed this in https://github.com/Dorus/yafc-ce/tree/subgroup-no-undo but i'm not 100% sure these are all the changes that are required to make this work.

**Comment by SWeini** [comment]
Just chiming in here with my personal opinion:

For a good user experience pure UI changes (like scrolling, open/close of nested tables, switching tabs) should not be part of undo history, but every undo/redo should jump to where the change was made (ideally even highlight the changes for a short time). This means that undo might need to switch tabs, scroll somewhere or open nested tables (in addition to the real change but never on its own).

Since that is not the case right now I'm not sure whether excluding open/close of nested tables really improves or degrades the experience.

**Comment by Dorus** [comment]
The thing with YaFC is that often I have receipt chains that are several pages long. If I change something at the bottom, I might want to know what changed on top. One thing our human eyes are very good at is spotting changes, so using undo / redo in succession allows me to make this comparison quickly.

That's where the issue with including collapse state in the undo history comes in, but also where jumping to changes wouldn't help. Sometimes the change I want to spot is in a collapsed subtree, so right now I need to open it, make the change again, and scroll all the way back to where I where.

**Comment by veger** [comment]
I use undo/redo usually with the same reason as @Dorus explained. I usually make sure to move the recipes I want to test, so they are next to each other, in opened subgroup state, make the change and then start running undo/redo cycles :smile: 

Quite a hassle, but sometimes I need to see if the 'change' is 'worth' it, especially if it involves a whole lot of building work.

So I agree with @SWeini that this might be a degradation in overall, but for this particular use-case it might be nice(r)...? For our use-case it would be nice if there are 2 screens, each with a different version of the undo buffer, so we can compare side-by-side or something...

**Comment by have-fun-was-taken** [comment]
Closed by https://github.com/have-fun-was-taken/yafc-ce/pull/26
