### ISSUE TITLE
Add shortcuts

### ISSUE THREAD

**Issue by have-fun-was-taken** [have-fun-was-taken/yafc-ce#35]
Make pressing Enter on keyboard equivalent of pressing the OK button. It's especially useful when creating a new production sheet. The form already closes on pressing Esc.

Optionally, make Ctrl+T equivalent to pressing "+" on top left. It's analogous to making a new tab in Firefox and Chrome.

**Comment by have-fun-was-taken** [comment]
If you have any other shortcuts in mind that would be awesome to add, write them down here :D

**Comment by veger** [comment]
Besides it being a new feature (request) I suppose we'd also need some more help/ideas to reach a complete feature and agreement... (so I added the HelpWanted tag as well)

**Comment by shihan42** [comment]
Listening to events on the Enter key needs careful consideration. In some dialogs like the mentioned "Create production sheet", there is only one blue button and the user would assume that enter presses that button.

Unfortunately, that can't be generalized. The welcome screen for example has several blues, but which one to choose? The most sensible answer would be the "Load '<projectname>'" button (that's something I'd like to have since ages ;) ). But I think the answer isn't that clear in other screens.

So I gathered some places:
1. The "Create page" dialogue for creating a production page or summary sheet
2. The filesystem dialog for "Save As"
3. The dialog for choosing data and mod folders
4. The milestones dialog (esc works already)
5. The preferences dialog (esc works already, too)
6. The "Check for updates" dialog (esc working)

Any other places that need enter (or another shortcut)?

**Comment by have-fun-was-taken** [comment]
Another cool behavior would be to set the modules of the building to the default ones on Right Mouse Button click, like clearing the filter in Factorio.

**Comment by have-fun-was-taken** [comment]
Removing the tag "help wanted" from this ticket to clarify that https://github.com/have-fun-was-taken/yafc-ce/issues/83 takes precedence.

**Comment by have-fun-was-taken** [comment]
Just dropping by to gush over RMB deleting rows and unlinking resources. It is awesome. Thank you!
