### ISSUE TITLE
sometimes search bars return nothing when there are items that match

### ISSUE THREAD

**Issue by apia46** [have-fun-was-taken/yafc-ce#74]
version 0.6.1.0
mods: pyanodons ae, text plates

i do not know how to reproduce this issue, but sometimes when i search for a production sheet it returns nothing even though i have sheets that should match the query
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/96461146/b448239e-4150-492e-b631-e23e603f4798)
(should show the page Vrauks among other things)

after this happened i tested a few letters to see what would show up. nothing did, until i inputted the letter I at which point it started behaving more or less reasonably

sometimes i search for something and even though its the first letter of what im looking for, the wanted page does not show up and instead other ones that somewhat match do

![image](https://github.com/have-fun-was-taken/yafc-ce/assets/96461146/9f6e3313-ba3f-49fe-a129-325738350e22)
(does not show Acetylene)
![image](https://github.com/have-fun-was-taken/yafc-ce/assets/96461146/6696529f-5b59-464a-a935-ba776836447e)
(does not show Plating even though it did in the previous image?)

i dont know what help i can give but here is the project file, the issue is not happening when i upload it though fdhjgbdsjkhfgdsfhlj
[bugged.yafc.txt](https://github.com/have-fun-was-taken/yafc-ce/files/14553686/bugged.yafc.txt)

**Comment by Beeka274** [comment]
may be relevant: i leave my computer on sleep alot, and sometimes yafc can be open* for dozens of hours

**Comment by Dorus** [comment]
I just had the same issue. Searching for "a" still returned quite a decent list of items, but adding any other letter, or any letter after "a" returned nothing.

I then tried a few things, including restarting YaFC, but before i could pinpoint the issue, it was working again.

Indeed my YaFC was running for a bit already, i've also noticed other issues with YaFC when it's running for some time (DPI settings mess up when it's running for a while).

**Comment by XhenZui** [comment]
I have a similar issue, but not sure if it's the same. I think it's caused by scrolling down in the list of pages before entering your search term.
See the scrollbar on the right-hand side.
![grafik](https://github.com/have-fun-was-taken/yafc-ce/assets/64024277/2f02f8ec-a086-4f99-9a88-d4182babdf20)

Now, with the entered search term - you can see the list is still scrolled down.
![grafik](https://github.com/have-fun-was-taken/yafc-ce/assets/64024277/04766c83-ec88-4b62-9cc4-b36558c3fec5)

Now, when I scroll up, I can actually see the thing I searched for. Also, the search window becomes much smaller, the moment the search result becomes visible
![grafik](https://github.com/have-fun-was-taken/yafc-ce/assets/64024277/f21064f9-e356-4bad-8412-fd5718bb74a9)
